version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync
    - uv pip install -e .
sphinx:
  configuration: docs/source/conf.py
