version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync --locked
    - cd docs && uv run --group docs make html
    - mkdir -p $READTHEDOCS_OUTPUT
    - mv docs/build/html $READTHEDOCS_OUTPUT

sphinx:
  configuration: docs/source/conf.py
