version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_install:
      - pip install poetry==1.8
      - poetry config virtualenvs.create false
      - poetry install --with docs

sphinx:
  configuration: docs/source/conf.py
