version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_create_environment:
      - pip install poetry==1.8
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs

sphinx:
  configuration: docs/source/conf.py
