version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync
    - make docs
    - cp -r docs/build/html $READTHEDOCS_OUTPUT
    - ls -la $READTHEDOCS_OUTPUT
    - ls -la $(READTHEDOCS_OUTPUT)html

sphinx:
  configuration: docs/source/conf.py
