name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: ci
    timeout-minutes: 10
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.18
    - name: Run Python commands
      run: |
        pip install --upgrade pip
        pip install poetry==1.6.1
    - name: Install dependencies
      run: |
        poetry install --with dev
    - name: Run checks
      run: |
        make checks
    - name: Download lczero weights
      run: |
        poetry run gdown 1Ssl4JanqzQn3p-RoHRDk_aApykl-SukE -O assets/tinygyal-8.pb.gz
        poetry run gdown 1WzBQV_zn5NnfsG0K8kOion0pvWxXhgKM -O assets/384x30-2022_0108_1903_17_608.pb.gz
        poetry run gdown 1erxB3tULDURjpPhiPWVGr6X986Q8uE6U -O assets/maia-1100.pb.gz
        poetry run gdown 1YqqANK-wuZIOmMweuK_oCU7vfPN7G_Z6 -O assets/t1-smolgen-512x15x8h-distilled-swa-3395000.pb.gz
    - name: Run tests
      run: |
        make tests
