on:
  workflow_call:
    inputs:
      tests-type:
        required: true
        type: string

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    environment: ci
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install just
      uses: extractions/setup-just@v3
      with:
        just-version: 1.41.0
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        uv sync --locked
    - name: Run checks
      run: |
        just checks
    - name: Download assets
      run: |
        just tests-assets
    - name: Run tests
      run: |
        just ${{ inputs.tests-type }}
    - name: Upload coverage reports to Codecov
      if: matrix.python-version == '3.10'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Upload test results to Codecov
      if: matrix.python-version == '3.10' && ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
