name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        uv sync --locked
    - name: Build package
      run: |
        uv build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
